baseurl = "https://keithkeekw.github.io/"
title = "keithkeekw@github"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "now/"
  url = "now/"

  [[params.navlinks]]
  name = "til/"
  url = "til/"
  
  
  #[[params.navlinks]]
  #name = "photos/"
  #url = "photos/"
